stages:
- name: test
  steps:
  - runScriptConfig:
      image: 172.26.126.67:280/public/sonar-scanner-cli:4.7
      shellScript: ls
    env:
      SONAR_HOST_URL: http://sonarqube.public-sonarqube:7343
      SONAR_LOGIN: 7f271b994783f3f2a083e512fab520f94b309916
  when:
    event:
      include:
      - push
- name: build
  steps:
  - runScriptConfig:
      image: 172.26.126.67:280/public/maven:3.6.1-jdk-8-alpine
      shellScript: |-
        ls
        mkdir -p /root/.m2 && mv deploy/settings.xml /root/.m2/
        mvn  clean  package -DskipTests
- name: publist
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/jpress:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: 172.26.126.67:280
timeout: 60
notification: {}
