stages:
- name: sonar-scanner
  steps:
  - runScriptConfig:
      image: 172.26.126.67:280/public/sonar-scanner-cli:4.7
      shellScript: ls
  when:
    event:
      include:
      - push
timeout: 60
notification: {}
